// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://hemkredzinaipjxnyqco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlbWtyZWR6aW5haXBqeG55cWNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzk1ODgsImV4cCI6MjA3MzYxNTU4OH0.EUhkSgAu1p3xAU7hkNVaWG9oHl_an6qZrrVGe93itaE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);